import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('http://localhost:38274/iframe.html?id=compositions-ae-opportunity-table--default&viewMode=story', { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
await p.screenshot({ path: '/tmp/opp-search-grey10.png', clip: { x: 0, y: 0, width: 900, height: 80 } });
await p.goto('http://localhost:38274/iframe.html?id=compositions-ae-account-table--default&viewMode=story', { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
await p.screenshot({ path: '/tmp/acc-search-grey10.png', clip: { x: 0, y: 0, width: 900, height: 80 } });
await b.close();
