// Hand-authored. The source of truth for this mode's semantic tokens.

export const ShellTokens = {
  "base": null,
  "surface": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "surface.alt": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "surface.accent": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "field": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "field.alt": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "ghost": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "ghost.field": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "ghost.highlight": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "brand": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "highlight": {
    "rest": null,
    "hover": null,
    "pressed": null,
    "selected": null,
    "disabled": null,
  },
  "text": {
    "primary": null,
    "secondary": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "tertiary": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "disabled": null,
    "placeholder": {
      "rest": null,
      "hover": null,
    },
    "brand": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "success": null,
    "danger": null,
    "warning": null,
    "caution": null,
    "ai": null,
    "link": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "link-neutral": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "link-visited": null,
  },
  "icons": {
    "primary": null,
    "secondary": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "tertiary": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "disabled": null,
    "placeholder": {
      "rest": null,
      "hover": null,
    },
    "brand": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "success": null,
    "danger": null,
    "warning": null,
    "caution": null,
    "ai": null,
    "link": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "link-neutral": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "link-visited": null,
  },
  "lines": {
    "info": null,
    "ai": null,
    "bold": null,
    "neutral": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "neutral-tile": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "brand": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "warning": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "caution": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "error": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
    "success": {
      "rest": null,
      "hover": null,
      "pressed": null,
      "disabled": null,
    },
  },
} as const;
